# Generated by Django 5.1.5 on 2025-02-01 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Județ',
                'verbose_name_plural': 'Județe',
            },
        ),
        migrations.CreateModel(
            name='FirmaProiectare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=1000)),
                ('adresa', models.CharField(max_length=512)),
                ('cui', models.CharField(max_length=20, unique=True)),
                ('nr_reg_com', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('cale_stampila', models.CharField(max_length=512)),
                ('cale_certificat', models.CharField(max_length=512)),
                ('judet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firme_proiectare', to='StudiiFezabilitate.judet')),
            ],
            options={
                'verbose_name': 'Firmă de proiectare',
                'verbose_name_plural': 'Firme de proiectare',
            },
        ),
        migrations.CreateModel(
            name='Localitate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('judet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localitati', to='StudiiFezabilitate.judet')),
            ],
            options={
                'verbose_name': 'Localitate',
                'verbose_name_plural': 'Localități',
                'unique_together': {('nume', 'judet')},
            },
        ),
        migrations.CreateModel(
            name='Inginer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=512)),
                ('telefon', models.CharField(max_length=20)),
                ('cnp', models.CharField(max_length=13, unique=True)),
                ('serie_ci', models.CharField(max_length=2)),
                ('numar_ci', models.CharField(max_length=10)),
                ('data_ci', models.DateField()),
                ('cale_ci', models.CharField(max_length=512)),
                ('cale_semnatura', models.CharField(max_length=512)),
                ('functie', models.CharField(max_length=100)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingineri', to='StudiiFezabilitate.firmaproiectare')),
                ('judet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingineri', to='StudiiFezabilitate.judet')),
                ('localitate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingineri', to='StudiiFezabilitate.localitate')),
            ],
            options={
                'verbose_name': 'Inginer',
                'verbose_name_plural': 'Ingineri',
            },
        ),
        migrations.AddField(
            model_name='firmaproiectare',
            name='localitate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firme_proiectare', to='StudiiFezabilitate.localitate'),
        ),
        migrations.CreateModel(
            name='Beneficiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=1000)),
                ('adresa', models.CharField(max_length=512)),
                ('cui', models.CharField(max_length=20, unique=True)),
                ('nr_reg_com', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('cale_stampila', models.CharField(max_length=512)),
                ('cale_certificat', models.CharField(max_length=512)),
                ('judet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiari', to='StudiiFezabilitate.judet')),
                ('localitate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiari', to='StudiiFezabilitate.localitate')),
            ],
            options={
                'verbose_name': 'Beneficiar',
                'verbose_name_plural': 'Beneficiari',
            },
        ),
        migrations.CreateModel(
            name='PersoanaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=512)),
                ('telefon', models.CharField(max_length=20)),
                ('cnp', models.CharField(max_length=13, unique=True)),
                ('serie_ci', models.CharField(max_length=2)),
                ('numar_ci', models.CharField(max_length=10)),
                ('data_ci', models.DateField()),
                ('cale_ci', models.CharField(max_length=512)),
                ('cale_semnatura', models.CharField(max_length=512)),
                ('functie', models.CharField(max_length=100)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persoane_contact', to='StudiiFezabilitate.firmaproiectare')),
                ('judet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persoane_contact', to='StudiiFezabilitate.judet')),
                ('localitate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persoane_contact', to='StudiiFezabilitate.localitate')),
            ],
            options={
                'verbose_name': 'Persoană de contact',
                'verbose_name_plural': 'Persoane de contact',
            },
        ),
        migrations.CreateModel(
            name='Lucrare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=1000)),
                ('nume_intern', models.CharField(max_length=255, unique=True)),
                ('adresa', models.CharField(max_length=512)),
                ('finalizata', models.BooleanField(default=False)),
                ('beneficiar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StudiiFezabilitate.beneficiar')),
                ('firma_proiectare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StudiiFezabilitate.firmaproiectare')),
                ('judet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lucrari', to='StudiiFezabilitate.judet')),
                ('localitate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lucrari', to='StudiiFezabilitate.localitate')),
                ('persoana_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StudiiFezabilitate.persoanacontact')),
            ],
            options={
                'verbose_name': 'Lucrare',
                'verbose_name_plural': 'Lucrări',
            },
        ),
        migrations.AddField(
            model_name='beneficiar',
            name='persoana_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiari', to='StudiiFezabilitate.persoanacontact'),
        ),
        migrations.CreateModel(
            name='Reprezentant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=512)),
                ('telefon', models.CharField(max_length=20)),
                ('cnp', models.CharField(max_length=13, unique=True)),
                ('serie_ci', models.CharField(max_length=2)),
                ('numar_ci', models.CharField(max_length=10)),
                ('data_ci', models.DateField()),
                ('cale_ci', models.CharField(max_length=512)),
                ('cale_semnatura', models.CharField(max_length=512)),
                ('functie', models.CharField(max_length=100)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprezentanti', to='StudiiFezabilitate.firmaproiectare')),
                ('judet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reprezentanti', to='StudiiFezabilitate.judet')),
                ('localitate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reprezentanti', to='StudiiFezabilitate.localitate')),
            ],
            options={
                'verbose_name': 'Reprezentant',
                'verbose_name_plural': 'Reprezentanți',
            },
        ),
        migrations.AddField(
            model_name='firmaproiectare',
            name='reprezentant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firme_proiectare', to='StudiiFezabilitate.reprezentant'),
        ),
    ]
