# Generated by Django 5.1.5 on 2025-02-07 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Loturi',
            },
        ),
        migrations.AddField(
            model_name='lucrare',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lucrari', to='StudiiFezabilitate.lot'),
        ),
    ]
