# Generated by Django 5.1.5 on 2025-02-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0002_lot_lucrare_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inginer',
            name='functie',
        ),
        migrations.RemoveField(
            model_name='persoanacontact',
            name='functie',
        ),
        migrations.AlterField(
            model_name='beneficiar',
            name='adresa',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiar',
            name='cale_certificat',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiar',
            name='cale_stampila',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiar',
            name='cui',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiar',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiar',
            name='judet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiari', to='StudiiFezabilitate.judet'),
        ),
        migrations.AlterField(
            model_name='beneficiar',
            name='localitate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiari', to='StudiiFezabilitate.localitate'),
        ),
        migrations.AlterField(
            model_name='beneficiar',
            name='nr_reg_com',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiar',
            name='persoana_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiari', to='StudiiFezabilitate.persoanacontact'),
        ),
        migrations.AlterField(
            model_name='beneficiar',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='firmaproiectare',
            name='cale_certificat',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='firmaproiectare',
            name='cale_stampila',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='firmaproiectare',
            name='reprezentant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='firme_proiectare', to='StudiiFezabilitate.reprezentant'),
        ),
        migrations.AlterField(
            model_name='firmaproiectare',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inginer',
            name='adresa',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='inginer',
            name='cale_ci',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='inginer',
            name='cale_semnatura',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='inginer',
            name='cnp',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inginer',
            name='data_ci',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inginer',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingineri', to='StudiiFezabilitate.firmaproiectare'),
        ),
        migrations.AlterField(
            model_name='inginer',
            name='judet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingineri', to='StudiiFezabilitate.judet'),
        ),
        migrations.AlterField(
            model_name='inginer',
            name='localitate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingineri', to='StudiiFezabilitate.localitate'),
        ),
        migrations.AlterField(
            model_name='inginer',
            name='numar_ci',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inginer',
            name='serie_ci',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='persoanacontact',
            name='adresa',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='persoanacontact',
            name='cale_ci',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='persoanacontact',
            name='cale_semnatura',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='persoanacontact',
            name='cnp',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persoanacontact',
            name='data_ci',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persoanacontact',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persoane_contact', to='StudiiFezabilitate.firmaproiectare'),
        ),
        migrations.AlterField(
            model_name='persoanacontact',
            name='judet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persoane_contact', to='StudiiFezabilitate.judet'),
        ),
        migrations.AlterField(
            model_name='persoanacontact',
            name='localitate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persoane_contact', to='StudiiFezabilitate.localitate'),
        ),
        migrations.AlterField(
            model_name='persoanacontact',
            name='numar_ci',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='persoanacontact',
            name='serie_ci',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reprezentant',
            name='adresa',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='reprezentant',
            name='cale_ci',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='reprezentant',
            name='cale_semnatura',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='reprezentant',
            name='data_ci',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reprezentant',
            name='functie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reprezentant',
            name='judet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reprezentanti', to='StudiiFezabilitate.judet'),
        ),
        migrations.AlterField(
            model_name='reprezentant',
            name='localitate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reprezentanti', to='StudiiFezabilitate.localitate'),
        ),
        migrations.AlterField(
            model_name='reprezentant',
            name='numar_ci',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reprezentant',
            name='serie_ci',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
