# Generated by Django 5.1.5 on 2025-02-08 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0003_remove_inginer_functie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmaproiectare',
            name='reprezentant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='firme_proiectare', to='StudiiFezabilitate.persoanacontact'),
        ),
        migrations.RemoveField(
            model_name='persoanacontact',
            name='firma',
        ),
        migrations.DeleteModel(
            name='Reprezentant',
        ),
    ]
