# Generated by Django 5.1.5 on 2025-02-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0004_alter_firmaproiectare_reprezentant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inginer',
            name='firma',
        ),
    ]
