# Generated by Django 5.1.5 on 2025-02-09 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0005_remove_inginer_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inginer',
            name='cnp',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CNP-ul trebuie să conțină exact 13 cifre', regex='^[0-9]{13}$')]),
        ),
        migrations.AlterField(
            model_name='inginer',
            name='numar_ci',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Numărul CI trebuie să conțină exact 6 cifre', regex='^[0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='inginer',
            name='serie_ci',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Seria CI trebuie să conțină exact 2 litere', regex='^[A-Za-z]{2}$')]),
        ),
        migrations.AlterField(
            model_name='persoanacontact',
            name='cnp',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CNP-ul trebuie să conțină exact 13 cifre', regex='^[0-9]{13}$')]),
        ),
        migrations.AlterField(
            model_name='persoanacontact',
            name='numar_ci',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Numărul CI trebuie să conțină exact 6 cifre', regex='^[0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='persoanacontact',
            name='serie_ci',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Seria CI trebuie să conțină exact 2 litere', regex='^[A-Za-z]{2}$')]),
        ),
    ]
