# Generated by Django 5.1.5 on 2025-02-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0006_alter_inginer_cnp_alter_inginer_numar_ci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localitate',
            name='tip',
            field=models.CharField(blank=True, choices=[('Municipiul', 'Municipiul'), ('Orașul', 'Orașul'), ('Comuna', 'Comuna')], max_length=16, null=True),
        ),
    ]
