# Generated by Django 5.1.5 on 2025-02-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0009_alter_lucrare_options_certificaturbanism_nume_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviz',
            options={'verbose_name': 'Aviz', 'verbose_name_plural': 'Avize'},
        ),
        migrations.AlterModelOptions(
            name='avizecu',
            options={'verbose_name': 'AvizCU', 'verbose_name_plural': 'AvizeCU'},
        ),
        migrations.AlterField(
            model_name='aviz',
            name='descriere',
            field=models.TextField(blank=True, null=True),
        ),
    ]
