# Generated by Django 5.1.5 on 2025-02-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0010_alter_aviz_options_alter_avizecu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avizecu',
            name='cale_aviz',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
