# Generated by Django 5.1.5 on 2025-02-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0011_alter_avizecu_cale_aviz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaturbanism',
            name='inginer_intocmit',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificat_urbanism_intocmit', to='StudiiFezabilitate.inginer'),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='inginer_verificat',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificat_urbanism_verificat', to='StudiiFezabilitate.inginer'),
        ),
    ]
