# Generated by Django 5.1.5 on 2025-02-28 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0013_alter_lucrare_beneficiar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avizecu',
            name='certificat_urbanism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avize_certificat', to='StudiiFezabilitate.certificaturbanism'),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='inginer_verificat',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificat_urbanism_verificat', to='StudiiFezabilitate.inginer'),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='lucrare',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat_urbanism', to='StudiiFezabilitate.lucrare'),
        ),
    ]
