# Generated by Django 5.1.5 on 2025-03-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0016_alter_avizecu_cost_net_alter_avizecu_cost_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avizecu',
            name='cost_net',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='avizecu',
            name='cost_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='avizecu',
            name='cost_tva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
