# Generated by Django 5.1.5 on 2025-03-23 12:30

import StudiiFezabilitate.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0017_alter_avizecu_cost_net_alter_avizecu_cost_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_CU',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_CU),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='valabilitate',
            field=models.PositiveIntegerField(default=12, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
