# Generated by Django 5.1.5 on 2025-03-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0018_alter_certificaturbanism_cale_cu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_CU',
            field=models.FileField(blank=True, null=True, upload_to='SF'),
        ),
    ]
