# Generated by Django 5.1.5 on 2025-03-30 13:27

import StudiiFezabilitate.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0019_alter_certificaturbanism_cale_cu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificaturbanism',
            name='cale_plan_situatie_PDF',
        ),
        migrations.RemoveField(
            model_name='certificaturbanism',
            name='cale_plan_topo_DWG',
        ),
        migrations.AddField(
            model_name='certificaturbanism',
            name='cale_plan_situatie_DWG',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_plan_situatie_DWG),
        ),
        migrations.AddField(
            model_name='certificaturbanism',
            name='cale_plan_situatie_la_scara',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_plan_situatie_la_scara),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_ATR',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_ATR),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_CU',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_CU),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_acte_beneficiar',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_acte_beneficiar),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_acte_facturare',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_acte_facturare),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_aviz_CTE',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_aviz_CTE),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_aviz_GIS',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_aviz_GIS),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_chitanta_APM',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_chitanta_APM),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_chitanta_DSP',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_chitanta_DSP),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_extrase_CF',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_extrase_CF),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_plan_incadrare_CU',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_plan_incadrare_CU),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_plan_situatie_CU',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_plan_situatie_CU),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='valabilitate',
            field=models.PositiveIntegerField(blank=True, default=12, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=60, message='Valoarea trebuie să fie mai mică sau egală cu 60.')]),
        ),
    ]
