# Generated by Django 5.1.5 on 2025-03-30 17:13

import StudiiFezabilitate.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0020_remove_certificaturbanism_cale_plan_situatie_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_ATR',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_ATR, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Fișierul trebuie să fie în format PDF'), StudiiFezabilitate.models.validate_file_mimetype_pdf]),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_CU',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_CU, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Fișierul trebuie să fie în format PDF'), StudiiFezabilitate.models.validate_file_mimetype_pdf]),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_acte_beneficiar',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_acte_beneficiar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Fișierul trebuie să fie în format PDF'), StudiiFezabilitate.models.validate_file_mimetype_pdf]),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_acte_facturare',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_acte_facturare, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Fișierul trebuie să fie în format PDF'), StudiiFezabilitate.models.validate_file_mimetype_pdf]),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_aviz_CTE',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_aviz_CTE, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Fișierul trebuie să fie în format PDF'), StudiiFezabilitate.models.validate_file_mimetype_pdf]),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_aviz_GIS',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_aviz_GIS, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Fișierul trebuie să fie în format PDF'), StudiiFezabilitate.models.validate_file_mimetype_pdf]),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_chitanta_APM',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_chitanta_APM, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Fișierul trebuie să fie în format PDF'), StudiiFezabilitate.models.validate_file_mimetype_pdf]),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_chitanta_DSP',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_chitanta_DSP, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Fișierul trebuie să fie în format PDF'), StudiiFezabilitate.models.validate_file_mimetype_pdf]),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_extrase_CF',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_extrase_CF, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Fișierul trebuie să fie în format PDF'), StudiiFezabilitate.models.validate_file_mimetype_pdf]),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_plan_incadrare_CU',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_plan_incadrare_CU, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Fișierul trebuie să fie în format PDF'), StudiiFezabilitate.models.validate_file_mimetype_pdf]),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_plan_situatie_CU',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_plan_situatie_CU, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Fișierul trebuie să fie în format PDF'), StudiiFezabilitate.models.validate_file_mimetype_pdf]),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_plan_situatie_DWG',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_plan_situatie_DWG, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['dwg'], message='Fișierul trebuie să fie în format DWG'), StudiiFezabilitate.models.validate_file_mimetype_dwg]),
        ),
        migrations.AlterField(
            model_name='certificaturbanism',
            name='cale_plan_situatie_la_scara',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_plan_situatie_la_scara, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Fișierul trebuie să fie în format PDF'), StudiiFezabilitate.models.validate_file_mimetype_pdf]),
        ),
    ]
