# Generated by Django 5.1.5 on 2025-04-13 13:05

import StudiiFezabilitate.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudiiFezabilitate', '0021_alter_certificaturbanism_cale_atr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaturbanism',
            name='cale_memoriu_tehnic_CU',
            field=models.FileField(blank=True, null=True, upload_to=StudiiFezabilitate.models.cale_upload_memoriu_tehnic_CU, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Fișierul trebuie să fie în format PDF'), StudiiFezabilitate.models.validate_file_mimetype_pdf]),
        ),
    ]
